<?php include "header_head.php"; ?>
	<title>Okan Özyiğit</title>
<?php include "header_nav.php"; ?>
		<div id="rev_slider_31_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="demo_minimalistic_portfolio" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
			<div id="rev_slider_31_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8.1">
				<ul>
					<li data-index="rs-85" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="800" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
						<img src="clip.png" alt="" data-bgposition="center center" data-bgfit="cover" class="rev-slidebg" data-no-retina>
						<div class="rs-background-video-layer" data-volume="mute" data-ytid="9t-R-_5LDX8" data-videoattributes="version=3&amp;enablejsapi=1&amp;html5=1&amp;hd=1&amp;wmode=opaque&amp;showinfo=0&amp;rel=0;" data-videorate="1" data-videowidth="100%" data-videoheight="100%" data-videocontrols="none" data-videoloop="none" data-aspectratio="16:9" data-autoplay="true" data-autoplayonlyfirsttime="false" data-nextslideatend="true"></div>
						<div class="tp-caption tp-layer-selectable rev_group" id="slide-85-layer-9" data-x="['left','left','center','center']" data-hoffset="['254','254','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['80','80','80','80']" data-width="95" data-height="40" data-whitespace="nowrap" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":10,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":10,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; min-width: 95px; max-width: 95px; max-width: 40px; max-width: 40px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
							<div class="tp-caption tp-layer-selectable tp-resizeme tp-svg-layer" id="slide-85-layer-8" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="28" data-height="28" data-whitespace="nowrap" data-type="svg" data-actions='[{"event":"click","action":"jumptoslide","slide":"previous","delay":""}]' data-svg_src="img/demo_minimalistic_portfolio/images/ic_keyboard_arrow_left_24px.svg" data-svg_idle="sc:transparent;sw:0;sda:0;sdo:0;" data-svg_hover="sc:transparent;sw:0;sda:0;sdo:0;" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; min-width: 28px; max-width: 28px; max-width: 28px; max-width: 28px; color: #ffffff;cursor:pointer;"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable tp-resizeme" id="slide-85-layer-10" data-x="['left','left','left','left']" data-hoffset="['30','30','30','30']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="27" data-height="1" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;background-color:rgba(255,255,255,0.3);"> </div>
							<div class="tp-caption tp-layer-selectable tp-resizeme tp-svg-layer" id="slide-85-layer-11" data-x="['left','left','left','left']" data-hoffset="['59','59','59','59']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="28" data-height="28" data-whitespace="nowrap" data-type="svg" data-actions='[{"event":"click","action":"jumptoslide","slide":"next","delay":""}]' data-svg_src="img/demo_minimalistic_portfolio/images/ic_keyboard_arrow_right_24px.svg" data-svg_idle="sc:transparent;sw:0;sda:0;sdo:0;" data-svg_hover="sc:transparent;sw:0;sda:0;sdo:0;" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11; min-width: 28px; max-width: 28px; max-width: 28px; max-width: 28px; color: #ffffff;cursor:pointer;"> </div>
						</div>
						<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable" id="slide-85-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"delay":10,"speed":10,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":10,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;background-color:rgba(20,20,20,0.8);"> </div>
						<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable" id="slide-85-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="['440','350','280','280']" data-height="2000" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;background-color:rgb(20,20,20);"> </div>
						<div class="tp-caption tp-layer-selectable" id="slide-85-layer-5" data-x="['left','left','center','center']" data-hoffset="['254','210','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-25','-25','0','0']" data-fontsize="['156','120','80','50']" data-lineheight="['210','160','110','70']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"split":"chars","splitdelay":0.1,"speed":1500,"split_direction":"forward","frame":"0","from":"x:[-105%];z:0;rX:0deg;rY:0deg;rZ:-90deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 78px; line-height: 105px; font-weight: 100; color: #ffffff; letter-spacing: 0px;font-family:Poppins;"><a href="video.php"><span>Video</span></a> </div>

					</li>
					<li data-index="rs-92" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="800" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
						<img src="02.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
						<div class="tp-caption tp-layer-selectable rev_group" id="slide-92-layer-9" data-x="['left','left','center','center']" data-hoffset="['254','254','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['80','80','80','80']" data-width="95" data-height="40" data-whitespace="nowrap" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":10,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":10,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; min-width: 95px; max-width: 95px; max-width: 40px; max-width: 40px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
							<div class="tp-caption tp-layer-selectable tp-resizeme tp-svg-layer" id="slide-92-layer-8" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="28" data-height="28" data-whitespace="nowrap" data-type="svg" data-actions='[{"event":"click","action":"jumptoslide","slide":"previous","delay":""}]' data-svg_src="img/demo_minimalistic_portfolio/images/ic_keyboard_arrow_left_24px.svg" data-svg_idle="sc:transparent;sw:0;sda:0;sdo:0;" data-svg_hover="sc:transparent;sw:0;sda:0;sdo:0;" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; min-width: 28px; max-width: 28px; max-width: 28px; max-width: 28px; color: #ffffff;cursor:pointer;"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable tp-resizeme" id="slide-92-layer-10" data-x="['left','left','left','left']" data-hoffset="['30','30','30','30']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="27" data-height="1" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;background-color:rgba(255,255,255,0.3);"> </div>
							<div class="tp-caption tp-layer-selectable tp-resizeme tp-svg-layer" id="slide-92-layer-11" data-x="['left','left','left','left']" data-hoffset="['59','59','59','59']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="28" data-height="28" data-whitespace="nowrap" data-type="svg" data-actions='[{"event":"click","action":"jumptoslide","slide":"next","delay":""}]' data-svg_src="img/demo_minimalistic_portfolio/images/ic_keyboard_arrow_right_24px.svg" data-svg_idle="sc:transparent;sw:0;sda:0;sdo:0;" data-svg_hover="sc:transparent;sw:0;sda:0;sdo:0;" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11; min-width: 28px; max-width: 28px; max-width: 28px; max-width: 28px; color: #ffffff;cursor:pointer;"> </div>
						</div>
						<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable" id="slide-92-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"delay":10,"speed":10,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":10,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;background-color:rgba(20,20,20,0.8);"> </div>
						<div class="tp-caption tp-shape tp-shapewrapper tp-layer-selectable" id="slide-92-layer-3" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="['440','350','280','280']" data-height="2000" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;background-color:rgb(20,20,20);"> </div>
						<div class="tp-caption tp-layer-selectable" id="slide-85-layer-5" data-x="['left','left','center','center']" data-hoffset="['254','210','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-25','-25','0','0']" data-fontsize="['156','120','80','50']" data-lineheight="['210','160','110','70']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"split":"chars","splitdelay":0.1,"speed":1500,"split_direction":"forward","frame":"0","from":"x:[-105%];z:0;rX:0deg;rY:0deg;rZ:-90deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 78px; line-height: 105px; font-weight: 100; color: #ffffff; letter-spacing: 0px;font-family:Poppins;"><a href="foto.php"><span>Fotoğraf</span></a> </div>
					</li>
				</ul>
				<div class="tp-bannertimer" style="height: 5px; background: rgba(255,58,45,0.15);"></div>
			</div>
		</div>
		<section id="gallery">
			<div class="container-fluid mt-15">
				<div class="brk-grid-fitrows" data-grid-cols="5" data-grid-cols-tablet="3" data-grid-height="378" data-brk-library="component__portfolio_row">
				
					<div class="brk-grid-fitrows__item">
						<div class="brk-simple-card-2 brk-simple-card-2_minimal">
							<div class="brk-simple-card-2__animation-wrapper" data-brk-library="component__portfolio_row,fancybox">
								<img class="brk-simple-card-2__img" src="ankarakapak.png" alt="alt">
								<div class="brk-simple-card-2__overlay brk-base-bg-11"></div>
								<div class="brk-simple-card-2__info text-center">
									<a class="brk-simple-card-2__category text-white font__family-montserrat font__size-12 font__weight-bold line__height-12 text-uppercase letter-spacing-100">06</a>
									<a class="brk-simple-card-2__title text-white font__family-roboto font__size-36 font__weight-ultralight line__height-38">Ankara</a>
								</div>
								<a class="brk-simple-card-2__btn fancybox" href="ankarakapak.png" data-fancybox="portfolio-rows-fancybox-group">
									<i class="far fa-plus icon-inside" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					</div>
					
					<div class="brk-grid-fitrows__item">
						<div class="brk-simple-card-2 brk-simple-card-2_minimal">
							<div class="brk-simple-card-2__animation-wrapper" data-brk-library="component__portfolio_row,fancybox">
								<img class="brk-simple-card-2__img" src="img/demo_minimalistic_portfolio/348x348_3.jpg" alt="alt">
								<div class="brk-simple-card-2__overlay brk-base-bg-11"></div>
								<div class="brk-simple-card-2__info text-center">
									<a class="brk-simple-card-2__category text-white font__family-montserrat font__size-12 font__weight-bold line__height-12 text-uppercase letter-spacing-100"></a>
									<a class="brk-simple-card-2__title text-white font__family-roboto font__size-36 font__weight-ultralight line__height-38">Ürün</a>
								</div>
								<a class="brk-simple-card-2__btn fancybox" href="img/demo_minimalistic_portfolio/348x348_3.jpg" data-fancybox="portfolio-rows-fancybox-group">
									<i class="far fa-plus icon-inside" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					</div>
					<div class="brk-grid-fitrows__item brk-grid-fitrows__item_width-2">
						<div class="brk-simple-card-2 brk-simple-card-2_minimal">
							<div class="brk-simple-card-2__animation-wrapper" data-brk-library="component__portfolio_row,fancybox">
								<img class="brk-simple-card-2__img" src="01.jpg" alt="alt">
								<div class="brk-simple-card-2__overlay brk-base-bg-11"></div>
								<div class="brk-simple-card-2__info text-center">
									<a class="brk-simple-card-2__category text-white font__family-montserrat font__size-12 font__weight-bold line__height-12 text-uppercase letter-spacing-100">06</a>
									<a class="brk-simple-card-2__title text-white font__family-roboto font__size-36 font__weight-ultralight line__height-38">Ankara</a>
								</div>
								<a class="brk-simple-card-2__btn fancybox" href="01.jpg" data-fancybox="portfolio-rows-fancybox-group">
									<i class="far fa-plus icon-inside" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					</div>
					
					<div class="brk-grid-fitrows__item">
						<div class="brk-simple-card-2 brk-simple-card-2_minimal">
							<div class="brk-simple-card-2__animation-wrapper" data-brk-library="component__portfolio_row,fancybox">
								<img class="brk-simple-card-2__img" src="ymk01.jpg" alt="alt">
								<div class="brk-simple-card-2__overlay brk-base-bg-11"></div>
								<div class="brk-simple-card-2__info text-center">
									<a class="brk-simple-card-2__category text-white font__family-montserrat font__size-12 font__weight-bold line__height-12 text-uppercase letter-spacing-100"></a>
									<a class="brk-simple-card-2__title text-white font__family-roboto font__size-36 font__weight-ultralight line__height-38">Yemek</a>
								</div>
								<a class="brk-simple-card-2__btn fancybox" href="ymk01.jpg" data-fancybox="portfolio-rows-fancybox-group">
									<i class="far fa-plus icon-inside" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	
        <?php include "footer.php"; ?>
		